### ISSUE TITLE
Warnings in test output 'observeDom: Requires MutationObserver support.'

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-ui-filter#16]
### How to Reproduce
yarn test:unit

### Expected behavior
No errors or warnings 

### Observed behavior
```
  ● Console

    console.warn node_modules/bootstrap-vue/dist/bootstrap-vue.common.js:1097
      [BootstrapVue warn]: observeDom: Requires MutationObserver support.
```

**Comment by arthurkirsz** [comment]
[BootstrapVue](https://bootstrap-vue.js.org/docs/misc/changelog/) removed the built in polyfills for Mutation Observer (Notes v2.0.0-rc.19) :


You need to provide a MutationObserver polyfill in your setup file (Got my answer via [stackoverflow](https://stackoverflow.com/questions/48809753/testing-mutationobserver-with-jest))

--- 

For example use a Polyfill like **mutationobserver-shim** :

`npm i -D mutationobserver-shim`

and add the polyfill in your setup file : 
```
const MutationObserver = require('mutationobserver-shim');
global.MutationObserver = MutationObserver;
```
