### ISSUE TITLE
on filter undefined it crashes

### ISSUE THREAD

**Issue by jelmerveen** [molgenis/molgenis-ui-filter#43]
### How to Reproduce
in dataexplorer 2 bookmarkable url branch, create a bookmark.
then open a new tab, paste in the bookmark and navigate to it.

in the code where it says: // Clean op the values by removing undefined entry's

### Expected behavior
do not crash

### Observed behavior
crashes

**Comment by connoratrug** [comment]
@jelmerveen  Could you create a reproduction using the molgenis-ui-filter repo ?, this would help fixing the issue

**Comment by jvanveen** [comment]
Won't fix (archiving repo)
